### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by uriva** [kensnyder/any-date-parser#35]
```
error: Uncaught (in promise) TypeError: Class constructor Rr cannot be invoked without 'new'
    at LocaleHelper.buildMonthNames (file:///home/uri/.cache/deno/npm/registry.npmjs.org/any-date-parser/1.5.4/src/LocaleHelper/LocaleHelper.js:132:25)
    at LocaleHelper.build (file:///home/uri/.cache/deno/npm/registry.npmjs.org/any-date-parser/1.5.4/src/LocaleHelper/LocaleHelper.js:86:9)
    at new LocaleHelper (file:///home/uri/.cache/deno/npm/registry.npmjs.org/any-date-parser/1.5.4/src/LocaleHelper/LocaleHelper.js:49:8)
    at Function.factory (file:///home/uri/.cache/deno/npm/registry.npmjs.org/any-date-parser/1.5.4/src/LocaleHelper/LocaleHelper.js:18:34)
    at Format.getRegExp (file:///home/uri/.cache/deno/npm/registry.npmjs.org/any-date-parser/1.5.4/src/Format/Format.js:74:47)
    at Format.getMatches (file:///home/uri/.cache/deno/npm/registry.npmjs.org/any-date-parser/1.5.4/src/Format/Format.js:90:28)
    at Format.attempt (file:///home/uri/.cache/deno/npm/registry.npmjs.org/any-date-parser/1.5.4/src/Format/Format.js:119:24)
    at Parser.attempt (file:///home/uri/.cache/deno/npm/registry.npmjs.org/any-date-parser/1.5.4/src/Parser/Parser.js:69:22)
```

**Comment by kensnyder** [comment]
This should be fixed in v2.x
